### ISSUE TITLE
Switch trackColor not working

### ISSUE THREAD

**Issue by aloptrbl** [galio-org/galio#101]
Switch trackColor true value and default string value not working changing color but false value working when changing to this: 
```
 <Switch 
 initialValue={false}
 trackColor={{true: 'white', false: 'green'}}
 thumbColor={'black'}
 onChange={() => Alert.alert('switch')} />
```

**Comment by shubhamkakkar** [comment]
You are unable to change the true color value because
its value could be only one of these
 'primary',  'theme', 'error',    'warning',   'success',  'info',

**Comment by palingheorghe** [comment]
fixed it and merged into `dev` branch
