### ISSUE TITLE
Article.js Screen of the application is not scrollable and hence some of the content is not displayed properly

### ISSUE THREAD

**Issue by shubhamkakkar** [galio-org/galio#102]
**Describe the bug**

**To Reproduce**
1. git clone https://github.com/galio-org/galio.git
cd galio
git checkout examples
npm install or yarn instal

2. open the code in code editor/IDE of your choice and navigate to routes.js file in the root of the directory

3. Scrolldown to commented code and uncomment the following code
```
Article: {
    screen: Article,
    navigationOptions: {
      drawerLabel: 'Article Screen',
      drawerIcon: props => (
        <MenuIcon name="flag" family="font-awesome" focused={props.focused} />
      ),
    },
  },
```
4. run command yarn start, open the app in expo and navigate to to the Article Screen by opening drawer
5. Compare the text displayed in the white box in the app with the code, 
---
  created by developers for developers.
"A lot of Bacon. I'd really like to eat like a LOT of Bacon :(."
---
this section is missing

**Comment by shubhamkakkar** [comment]
### I am taking this

**Comment by palingheorghe** [comment]
Thanks for this issue @shubhamkakkar !

**Comment by palingheorghe** [comment]
Moved the galio-app to another repo called [galio-starter-kit](https://github.com/galio-org/galio-starter-kit). So all the issues regarding the app need to move there as well. Thank you! 🧜🏽‍♂️
