### ISSUE TITLE
Great Library

### ISSUE THREAD

**Issue by abodehq** [galio-org/galio#119]
just i want to know what platform u used to build your website https://galio.io/ i will be more than happy if you can let me know what u used.

thanks

**Comment by palingheorghe** [comment]
Hi @abodehq ! Galio's using jekyll with gh-pages for the website. The design is inspired by Google's Material Design. 

Alin

**Comment by abodehq** [comment]
thank you very much really appreciate your reply, is any theme template u were using along with jekyll to support google material ui ?

**Comment by palingheorghe** [comment]
Nope, created from scratch.
