### ISSUE TITLE
Icon.js component problem in Expo SDK v33

### ISSUE THREAD

**Issue by pejoujarrar** [galio-org/galio#122]
**Describe the bug**
I wanted to upgrade Expo SDK to atleast v33 in order to put the app in play store as it requires at least an API Level of 28. By doing it I've encountered the error discussed [here](https://github.com/galio-org/galio/issues/93) .
Then by upgrading galio-framework from v 0.4.x to v 0.5.2 I am facing another problem in the component Icon.js:

**Screenshots**
![voila](https://user-images.githubusercontent.com/49135588/63986366-8d2c9280-cb0e-11e9-83e6-4be2fa67f706.png)

**Smartphone (please complete the following information):**
 - Device: Iphone 6
 - Type of device: physical
 - OS: iOS 8.1
 - React-Native version: sdk 33
 - Expo version: 33.0.0

Thank you.

**Comment by palingheorghe** [comment]
Hi @pejoujarrar ! Could you send me a snippet of your code just so I can see what exactly are you using from `galio-framework`? Also could you please go to your `node_modules` folder, search for `galio-framework` and verify if it looks identical to our `master` branch?

**Comment by pejoujarrar** [comment]
Hi @palingheorghe,

Thank you for the answer, I tried to clone the branch directly in the project. The problem is situated in the file src/Icon.js. Expo is not longer able to load ./font/galio.ttf Here is the error: 

![error](https://user-images.githubusercontent.com/49135588/64137486-78643d80-ce33-11e9-9cbc-d6da9044be78.png)

The load of ttf file is done in this line: 

`const Galio = createIconSetFromIcoMoon(galioConfig, 'Galio', './fonts/galio.ttf');

// Galio Fonts have to be linked with 'react-native link' if you're using react-native-cli
// Galio Fonts have to loaded with Fonts.loadAsync if you're
// using Expo (you can export GalioFont from index in order to import it)`

As for the use of Galio, that generates the error, here is the code:

`import React from 'react';
import * as Font from 'expo-font'
import { createIconSetFromIcoMoon } from '@expo/vector-icons';
import { Icon } from 'galio-framework';

import GalioConfig from '../assets/fonts/galioExtra';


const GalioExtra = require('../assets/fonts/galioExtra.ttf');
const IconGalioExtra = createIconSetFromIcoMoon(GalioConfig, 'GalioExtra');

export default class IconExtra extends React.Component {
  state = {
    fontLoaded: false,
  }

  async componentDidMount() {
    await Font.loadAsync({ GalioExtra: GalioExtra });
    this.setState({ fontLoaded: true });
  }

  render() {
    const { name, family, ...rest } = this.props;
    
    if (name && family && this.state.fontLoaded) {
      if (family === 'GalioExtra') {
        return <IconGalioExtra name={name} family={family} {...rest} />;
      }
      return <Icon name={name} family={family} {...rest} />;
    }

    return null;
  }
}
`

Thank you

**Comment by DadaConsultant** [comment]
I have the same issue. Any luck on this pls @palingheorghe? 

@pejoujarrar have you been able to resolve yours

**Comment by pejoujarrar** [comment]
@DadaConsultant , Unfortunately, still no progress.

**Comment by palingheorghe** [comment]
Ok guys so I managed to get somewhere regarding that warning. 

You have to remove the prop called `family` if you're using the component from `createIconSetFromIcoMoon`. 

I init a new Expo app and played around with the Icon in the default App.js file. 
This is my code: 
```jsx
import React from 'react';
import { StyleSheet, View } from 'react-native';
import { createIconSetFromIcoMoon } from '@expo/vector-icons';
import { Icon, galioConfig, GalioFont } from 'galio-framework';

const IconGalioExtra = createIconSetFromIcoMoon(galioConfig, "Galio", GalioFont);

export default function App() {
  return (
    <View style={styles.container}>
      <IconGalioExtra name="bag" size={40} color="#50C7C7" />
      <Icon name="bag" family="Galio" size={40} color="#50C7C7"/>
    </View>
  );
}
```

Both icons show up as expected in the simulator. 

Hope this'll help you out @pejoujarrar @DadaConsultant ! 🧜🏽‍♂️⭐️

**Comment by pejoujarrar** [comment]
@palingheorghe Thank you very much, waiting for @DadaConsultant to confirm the solution you mentionned. 

As for me i managed to solve the problem by not using any Icon from Galio family. Here is the list of families that can be used: 

> zocial, octicon, material, material-community, ionicon, foundation, evilicons, entypo, font-awesome, simple-line-icon, feather, antdesign, material-icon

So i just replaced the family of icons I was using from Galio to an equivalent to this icons in the other families. Now everything is working. 

Thank you for the support.

**Comment by varunrachakatla** [comment]
import React from 'react';
import * as Font from 'expo-font';

import { Ionicons } from '@expo/vector-icons';

import { createIconSetFromIcoMoon } from 'react-native-vector-icons';
import PropTypes from 'prop-types';

import GalioTheme, { withGalio } from './theme';
import galioConfig from './fonts/galio';

Ionicons.Galio = createIconSetFromIcoMoon(galioConfig, 'Galio');
const GalioFont = require('./fonts/galio.ttf');

class Icon extends React.Component {
  state = {
    fontLoaded: false,
  };

  async componentDidMount() {
    await Font.loadAsync({
      Galio: GalioFont,
    });

    this.setState({ fontLoaded: true });
  }

  render() {
    const { name, family, size, color, styles, theme, ...rest } = this.props;
    const { fontLoaded } = this.state;
    const { [family]: IconInstance } = Ionicons;

    if (name && IconInstance && fontLoaded) {
      return (
        <IconInstance
          name={name}
          size={size || theme.SIZES.BASE}
          color={color || theme.COLORS.BLACK}
          {...rest}
        />
      );
    }

    return null;
  }
}

Icon.defaultProps = {
  name: null,
  family: null,
  size: null,
  color: null,
  styles: {},
  theme: GalioTheme,
};

Icon.propTypes = {
  name: PropTypes.string,
  family: PropTypes.string,
  size: PropTypes.number,
  color: PropTypes.string,
  styles: PropTypes.any,
  theme: PropTypes.any,
};

export default withGalio(Icon);





i just replaced the Icons with Ionicons which is deprecated in sdk 33
also i just added a copy of galio.json from config in font folder this solved the issue completely

**Comment by palingheorghe** [comment]
I'm glad you managed to solve your problem if you ever encounter more problems like this please refer to my comment above.

🧜🏽‍♂️🧞‍♂️

**Comment by stephanierobison** [comment]
The above fix didn't work for me and I've spent the past 3 hours trying not to slam my face into my desk.   Upgrading from Expo 32 to 35 has been a nightmare.

I ended up being able to the issue with changing the node_modules/galio-framework/Icon.js from 
```
const Galio = createIconSetFromIcoMoon(galioConfig, 'Galio', './fonts/galio.ttf');
```
 to 
```
const GalioFont = require('./fonts/galio.ttf');

const Galio = createIconSetFromIcoMoon(galioConfig, 'Galio', GalioFont);
```
