### ISSUE TITLE
Reference Error: Can't find variable: theme

### ISSUE THREAD

**Issue by sonugk** [galio-org/galio#130]
**Describe the bug**
I upgraded from `galio-framework` version `0.5.3` to `0.6.0` and getting below error.
I am using creative-tim's argon free theme bvased on galio `0.5.3`

**To Reproduce**
1. Upgrade from any galio 0.5.3 project to 0.6.0, sample project which I am using [is here](https://www.creative-tim.com/product/argon-react-native)
2. Run the project using Expo and you will see above error

**Expected behavior**
Expected the upgrade to work out of the box or some migration guide to be provided

**Screenshots**
![image](https://user-images.githubusercontent.com/12816063/64920459-9e51f080-d7ea-11e9-93cf-586fab6c99db.png)

**Smartphone (please complete the following information):**
 - I am using Genymotion Samsung Galaxy S9 device
 - Type of device: simulator
 - OS: API26
 - React-Native version: 0.60.4
 - Expo version: 34.0.4

**Comment by sonugk** [comment]
After digging donw found it was missing parameter `theme` in Checkbox function in `node-modules\galio-framework\Checkbox.js` line no 79. I have used this local solution for now.
Please check highlighted items in image

![image](https://user-images.githubusercontent.com/12816063/64924929-61065680-d81c-11e9-96f7-606de2ef4dba.png)

**Comment by palingheorghe** [comment]
Hi @sonugk ! As I can see adding `theme` as a prop solved your issue. I'll make sure to update the library with your solution asap. 

Alin 🧜🏽‍♂️

**Comment by sonugk** [comment]
@palingheorghe
 Okay thanks a lot.

**Comment by palingheorghe** [comment]
Closed the issue because I pushed a hotfix regarding these issues. You can find out more about this hotfix here: https://github.com/galio-org/galio/releases/tag/v0.6.1
