### ISSUE TITLE
can't find variable: style" in Card (at theme.index.js:33) , can't fins variable: props" in Card (at theme.index.js:33)

### ISSUE THREAD

**Issue by Conceptx** [galio-org/galio#132]
**Describe the bug**

**To Reproduce**
1. Install galio-framework in react-native project; 
2. import { Card } from 'galio-framework';
3. use card example defined on galio.io
4. run react-native run-android to see error on device.

**Expected behavior**
To see galio card component as shown or similar to the one provided on galio.io

**Smartphone:**
 - Device: Samsung Galaxy Grand Prime [Physical Device] + , Pixel 2 [Emulator]
 - OS: Android 6.0
 - React-Native version: 0.60.5
 - Galio-Framework version : ^0.6.0
 - Expo version: no expo

**Comment by palingheorghe** [comment]
Hi @Conceptx ! Thanks for pointing this out! Your commit doesn't really solve the issue, I've posted a solution which will be implemented as fast as possible: #134 .

Thanks, I'll close the conversation and we can move it there. 🧜🏽‍♂️
