### ISSUE TITLE
Card: ReferenceError: Can't find variable style

### ISSUE THREAD

**Issue by seyaobey** [galio-org/galio#134]
**Describe the bug**
First time using the Galio framework (I am using it along with the argon template).
I am adding the Card component in my screen:

```
import { Card } from 'galio-framework';

...

<Card title={myTitle} />
```

**Expected behavior**
Card component should mount with any issue

But this is what I'm getting:

**Screenshots**
<img width="375" alt="File_001" src="https://user-images.githubusercontent.com/2738569/65724527-e1487980-e0b0-11e9-8847-0849d585cb7a.png">

**Smartphone (please complete the following information):**
 - Device: iPhone Xr
 - Type of device: physical
 - React-Native version: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz
 - Expo version: sdk-34

**Additional context**
I am using Galio with the Argon Template. (https://github.com/creativetimofficial/argon-react-native). I don't know if this error comes from the template.

**Comment by GustavoBlaze** [comment]
It's happen with me too, and i'm use just the Galio

**Comment by palingheorghe** [comment]
Hi @seyaobey @GustavoBlaze ! Thanks for pointing this out! This is a problem with our Card component which we need to solve asap. As far as I can see if you add the `style` prop and replace `...rest` with `...props` at the beginning of the function, everything is solved. 

Thanks 🧜🏽‍♂️

**Comment by presola** [comment]
this is also the same for Text and Block components

**Comment by AbdurRehman26** [comment]
I cant seem to pass dynamic image url to card as well. Anyone here has done it ?

**Comment by AbdurRehman26** [comment]
> Hi @seyaobey @GustavoBlaze ! Thanks for pointing this out! This is a problem with our Card component which we need to solve asap. As far as I can see if you add the `style` prop and replace `...rest` with `...props` at the beginning of the function, everything is solved.
> 
> Thanks 🧜🏽‍♂️

Doing this works but for only static image paths. i can not pass a variable as prop for image

**Comment by palingheorghe** [comment]
@presola the `style` prop should work as intended for the `Block` component. `Text` apparently has the same issue which can be solved by adding `style` in the prop section of the function in the `text.js` file of our component. We will solve this asap with the next hotfix.

@AbdurRehman26 I'm glad the fix worked! Could you please send a code snippet of the way you\'re adding the dynamic image please?

**Comment by palingheorghe** [comment]
This specific issue should be solved now for Card and Text components. [Release info for v0.6.3](https://github.com/galio-org/galio/releases/tag/v0.6.3) [Release info for v0.6.2](https://github.com/galio-org/galio/releases/tag/v0.6.2)
