### ISSUE TITLE
Change font for entire app

### ISSUE THREAD

**Issue by somilmathur** [galio-org/galio#136]
Hey I've started using Galio and find it very useful, however, I can't figure out how to change the fontFamily for the whole app? Can anyone help me out with that?

**Comment by SaadQamar01** [comment]
@somilmathur you can follow this article https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e

**Comment by palingheorghe** [comment]
Closed the issue due to the fact that it's old and inactive.

**Comment by sinafbd** [comment]
have you find the solution?
