### ISSUE TITLE
DeckSwiper defaulting to top Flexbox position

### ISSUE THREAD

**Issue by llcamp** [galio-org/galio#144]
**Describe the bug**
When a class is created utilizing the DeckSwiper component, exported and added in another component that handles the view, if said component is styled with Flexbox, it will create an issue where all of the other elements/components added below will default to the top of the view. 

**To Reproduce**
1. Create a DeckSwiper component. 
2. Export the component to a new .js file
3. In the file <View> add the component DeckSwiper and below add a different component or class (I've added Button and Text components)

**Expected behavior**
The behavior should be that the any component added below the DeckSwiper component, with a Flexbox style should display below.

**Screenshots**
<img width="865" alt="Captura de Pantalla 2019-10-21 a la(s) 16 42 30" src="https://user-images.githubusercontent.com/19616837/67248517-fac7b180-f421-11e9-8f92-e58b3b799ba7.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone XR]
 - Type of device: [e.g Xcode simulator]
 - OS: [e.g. iOS12.4]
 - React-Native version: [e.g. 0.59.8]
 - Expo version: [e.g. 2.21.2]

**Comment by palingheorghe** [comment]
Hi @llcamp ! Have you tried encapsulating the `<LugarSwiper />` in another `<Block />` component? this should be done in the `topFive` class. As far as I can see the `<Button />` component was suppose to come after the Swiper but the Swiper isn't rendering for some reason.

**Comment by llcamp** [comment]
Hello! In this particular case <LugarSwiper/> is the component that renders the Swiper, I just implemented it in a different class so it can be less cluttered. Let me know if that answers your question and if you need any more info. Glad to help!

**Comment by palingheorghe** [comment]
Is the component populated as written in the docs? (with the proper array of elements)
Just try something like this to see if this solves the layout issue: 
```jsx
<View styles={styles.viewSwiper}>
 <View>
   <Text>Example text</Text>
 </View>
 <Block>
   <LugarSwiper />
 </Block>
<Button title="Example button" />
</View>
```
import the `Block` component from `galio-framework`

**Comment by palingheorghe** [comment]
closed the issue for inactivity
