### ISSUE TITLE
navbar back icon very small (almost not visible)

### ISSUE THREAD

**Issue by BechirAhmed** [galio-org/galio#147]
I have a problem with the navbar back icon, it's very small, and i couldn't change it.
![fullsizeoutput_66](https://user-images.githubusercontent.com/18298101/69338510-4658bf80-0c5b-11ea-9118-3478f7ac4373.jpeg)
![fullsizeoutput_64](https://user-images.githubusercontent.com/18298101/69338511-46f15600-0c5b-11ea-9baa-a7254ec9a759.jpeg)

there is the difference between left icon generally and back icon
```js
<NavBar
  back={back}
  ...
  left={
    <Icon
         name={back ? 'nav-left' : "menu-8"} family="ArgonExtra"
         size={14} onPress={this.handleLeftPress}
         color={iconColor || argonTheme.COLORS.WHITE}/>
        }
  {...props}
/>
```
I have tried to change icon size but the problem is in pages where back props included this left icon doesn't effect, seems like that the back props has its own icon and styles somewhere.

**Comment by palingheorghe** [comment]
Hi @BechirAhmed ! Try to remove the back prop. Because of a bug with the `<NavBar />` component you'd have to only specify the `left` prop. We will solve this as soon as possible.

**Comment by palingheorghe** [comment]
Closed because we've merged the PR into the `dev` branch. Thank you!
