### ISSUE TITLE
withGalio() does not forward refs to wrapped components

### ISSUE THREAD

**Issue by AndyOsei** [galio-org/galio#185]
**Describe the bug**
Ref for a component passed to the withGalio higher-order component does not get forwarded to the wrapped component but rather references the outermost container component. 

**To Reproduce**
```
import React from "react";
import { TextInput, StyleSheet } from "react-native";
import { withGalio, Block, Button, theme } from "galio-framework";

const Input = React.forwardRef((props, ref) => {
  const { theme, ...rest } = props;
  return (
    <TextInput
      {...{ ref, ...rest }}
      placeholder="name"
      style={{
        width: 250,
        height: 45,
        padding: 10,
        borderColor: theme.COLORS.MUTED,
        borderWidth: 1,
        marginRight: 10
      }}
    />
  );
});

const MyInput = withGalio(Input);

export default function App() {
  const inputRef = React.useRef(null);

  const handlePress = () => {
    if (inputRef.current) {
      inputRef.current.clear();
    }
  };

  return (
    <Block flex middle>
      <Block row style={styles.wrapper}>
        <MyInput ref={inputRef} />
        <Button onPress={handlePress} style={{ width: 100 }}>
          clear
        </Button>
      </Block>
    </Block>
  );
}

const styles = StyleSheet.create({
  wrapper: {
    height: 50
  }
});
```
It throws an error  
```inputRef.current.clear is not a function. (In 'inputRef.current.clear()', inputRef.current.clear is undefined)```

**Expected behavior**
The TextInput value should clear onPress of the button.

**Screenshots**
<img width="375" alt="Screenshot 2020-02-22 at 12 11 47 AM" src="https://user-images.githubusercontent.com/17987074/75081764-56a56280-5508-11ea-95e9-36c829564360.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - Type of device: ios simulator
 - OS: iOS 13.3
 - React-Native version: 0.59
 - Expo version: 35.0.0

**Additional context**

**Comment by palingheorghe** [comment]
i'll have to look into this, if someone has any idea how to solve this faster please do help out

**Comment by AndyOsei** [comment]
i will open a PR to fix it...

**Comment by palingheorghe** [comment]
Closed because we've merged the PR into the `dev` branch. Thank you!
