### ISSUE TITLE
Enhancement: Allow style customisations for label content and help content

### ISSUE THREAD

**Issue by robertqin86** [galio-org/galio#196]
**Is your feature request related to a problem? Please describe.**
The help and label text styles are currently hardcoded and not customisable.  

**Describe the solution you'd like**
Custom styles for the help and label text styles should be injected via props and override the default `styles.label` and `styles.helpText`.

**Comment by robertqin86** [comment]
Please review and consider PR: https://github.com/galio-org/galio/pull/197

**Comment by palingheorghe** [comment]
Closed because we've merged this issue into `dev`
