### ISSUE TITLE
Require Help On NavBar Header

### ISSUE THREAD

**Issue by anandtechmedia** [galio-org/galio#198]
Hi All,

Greetings!

We have been trying to make the following changes to the NavBar. But couldn't achieve them yet.

1. Passing dynamic values through renderRight icons.
2. Change the header title dynamically. 
3. Add OnPress event to the Header Title.
4. Add an icon dynamically before the header title.
5. The "Back" trigger should refresh the page.

Can anyone help us with this?

Thanking you,

Best Regards,
Saran

**Comment by AndyOsei** [comment]
@anandtechmedia, can you please provide a reproducible example of what you’ve tried so far in order to investigate and tell you why it ddn’t work or give you alternatives as to how to accomplish them...

**Comment by anandtechmedia** [comment]
Hi Andy,

Thank you for your response.

This is my header component,

`import React from 'react';
import { withNavigation } from '@react-navigation/compat';
import { TouchableOpacity, StyleSheet, Platform, Dimensions } from 'react-native';
import { Button, Block, NavBar, Input, Text, theme } from 'galio-framework';

import Icon from './Icon';
import materialTheme from '../constants/Theme';

const { height, width } = Dimensions.get('window');
const iPhoneX = () => Platform.OS === 'ios' && (height === 812 || width === 812 || height === 896 || width === 896);

const AddEditButton = ({isWhite, style, navigation}) => (
  <TouchableOpacity style={[styles.button, style]} onPress={() => navigation.navigate('MyGroup')}>
    <Icon
      size={16}
      family="entypo"
      name="plus"
      color={theme.COLORS[isWhite ? 'WHITE' : 'ICON']}
    />
  </TouchableOpacity>
);

class Header extends React.Component {
  handleLeftPress = () => {
    const { back, navigation } = this.props;
    return (back ? navigation.goBack() : navigation.openDrawer());
  }

  renderRight = () => {
    const { white, title, rightIcon, navigation } = this.props;

    switch (rightIcon){
        case 'Photo':
          return ([
            <AddEditButton key='my-group' navigation={navigation} isWhite={white} />,
      ]);
      default:
        break;
    }
  }

  renderSearch = () => {
    const { navigation } = this.props;
    return (
      <Input
        right
        color="black"
        style={styles.search}
        placeholder="Search..."
        onFocus={() => navigation.navigate('Pro')}
        iconContent={<Icon size={16} color={theme.COLORS.MUTED} name="magnifying-glass" family="entypo" />}
      />
    )
  }


  renderHeader = () => {
    const { search, tabs } = this.props;
    if (search || tabs) {
      return (
        <Block center>
          {search ? this.renderSearch() : null}
          {tabs ? this.renderTabs() : null}
        </Block>
      )
    }
    return null;
  }

  render() {
    const { back, title, white, transparent, navigation } = this.props;
    // const { routeName } = navigation.state;
    const noShadow = ["Home","Search", "Categories", "Deals", "Pro", "Profile"].includes(title);
    const headerStyles = [
      !noShadow ? styles.shadow : null,
      transparent ? { backgroundColor: 'rgba(0,0,0,0)' } : null,
    ];

    return (
      <Block style={headerStyles}>
        <NavBar
          back={back}
          title={title}
          style={styles.navbar}
          transparent={transparent}
          right={this.renderRight()}
          rightStyle={{ alignItems: 'center' }}
          leftStyle={{ flex: 0.3, paddingTop: 2  }}
          leftIconName={(back ? 'chevron-left' : 'navicon')}
          leftIconColor={white ? theme.COLORS.WHITE : theme.COLORS.ICON}
          titleStyle={[
            styles.title,
            {color: theme.COLORS[white ? 'WHITE' : 'ICON']},
          ]}
          onLeftPress={this.handleLeftPress}
        />
        {this.renderHeader()}
      </Block>
    );
  }
}

export default withNavigation(Header);

const styles = StyleSheet.create({
  button: {
    padding: 12,
    position: 'relative',
  },
  title: {
    width: '100%',
    fontSize: 24,
    fontWeight: 'bold',
    //backgroundColor:"#f6f6f6",
    textAlign: "center",
    
  },
  navbar: {
    paddingVertical: 0,
    paddingBottom: theme.SIZES.BASE * 1.5,
    paddingTop: iPhoneX ? theme.SIZES.BASE * 4 : theme.SIZES.BASE,
    zIndex: 5,
  },
  shadow: {
    backgroundColor: theme.COLORS.WHITE,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    shadowOpacity: 0.2,
    elevation: 3,
  },
  notify: {
    backgroundColor: materialTheme.COLORS.LABEL,
    borderRadius: 4,
    height: theme.SIZES.BASE / 2,
    width: theme.SIZES.BASE / 2,
    position: 'absolute',
    top: 8,
    right: 8,
  },
  header: {
    backgroundColor: theme.COLORS.WHITE,
  },
  divider: {
    borderRightWidth: 0.3,
    borderRightColor: theme.COLORS.MUTED,
  },
  search: {
    height: 48,
    width: width - 32,
    marginHorizontal: 16,
    borderWidth: 1,
    borderRadius: 3,
  },
  tabs: {
    marginBottom: 24,
    marginTop: 10,
    elevation: 4,
  },
  tab: {
    backgroundColor: theme.COLORS.TRANSPARENT,
    width: width * 0.50,
    borderRadius: 0,
    borderWidth: 0,
    height: 24,
    elevation: 0,
  },
  tabTitle: {
    lineHeight: 19,
    fontWeight: '300'
  },
})`

1. We try to give `navigation.getParam("navTitle", "")` to "tite" instead of `title={title}` inside the <NavBar> tag, so that we can use `navigation.setParam("navTitle","Dynamic Title")`. 
2. We are unsure about how to add a link (dynamically through onPress) to the header title with or without passing a value to the next screen.
3. We are unsure about how to add an icon (dynamically) before the header title.
4. Also, we are finding it hard getting the back button to reload the screen to get the latest values.

We are very new to React-Native and have tried a lot of options over the past couple of months. Finally, we find Galio very easy, but just got stuck with these minor items.

Thank you for your help!

Best Regards,
Saran

**Comment by AndyOsei** [comment]
@anandtechmedia for point 1, 2 & 3, You can pass a custom component that does what you want to title prop like this `title={<Component  onPress={your onPress here} icon={your icon here} />}` 

For point 4, pass false to the back prop and define  a custom button in the renderRight function to do what you want.

Do lemme know if you have any other questions, need further clarification or if the above helps you solves your issues.

**Comment by anandtechmedia** [comment]
Hi Andy,

Wow!! It works like charm!! 

Thanks for your Great Support!!

Best Regards,
Saran

**Comment by AndyOsei** [comment]
@anandtechmedia Glad I could help.
