### ISSUE TITLE
Alternative for Typography "p" property 

### ISSUE THREAD

**Issue by hetmann** [galio-org/galio#2]
For easy understanding what `p` represent, we can name it `paragraph`

https://github.com/galio-org/galio/blob/ff9d4727fef2fc590da33b1875bfbdf0eee83492/src/Typography.js#L17

**Comment by hetmann** [comment]
I would respect the naming convention for Typography using the following guidelines:
- https://material.io/design/typography/the-type-system.html#type-scale
- https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/

**Comment by misircoder** [comment]
I think p is better & shorter than paragraph 👍

**Comment by hetmann** [comment]
The **Typography** component was renamed to **Text** and the paragraph is accessed with **p** prop
