### ISSUE TITLE
Change color of button text

### ISSUE THREAD

**Issue by willroyMyles** [galio-org/galio#201]
Would be great to be able to change the color of text inside a button

**Comment by AndyOsei** [comment]
You can do so by passing a  style object to textStyle prop like

````
<Button textStyle={{color: ‘red’}}>send</Button>
````

Do let me know if it solves your issue...

**Comment by willroyMyles** [comment]
quick question, how did you guys achive the colored drop shadow effect on buttons?

**Comment by AndyOsei** [comment]
Could you elaborate more on what you mean..??
