### ISSUE TITLE
Radio: No way to change Radio button state.

### ISSUE THREAD

**Issue by shivanshseth** [galio-org/galio#202]
**Is your feature request related to a problem? Please describe.**
While using radio buttons, I need to make sure that only one of them is active at a time. For this I need some prop to switch it on/off.
**Describe the solution you'd like**
A prop (can call is selected) to control its state.

**Describe alternatives you've considered**
react-native-material-ui component for RadioButton

**Additional context**

**Comment by StheffanyHadlich** [comment]
The current radio button has an `initialValue` property that is used to control the radio button internal state with a `checked` value. Is it no behaving properly?

**Comment by AndyOsei** [comment]
A fix for that and others will be released soon in a minor/patch version...

**Comment by palingheorghe** [comment]
Stheffany is right, `initialValue` solves the issue. The thing that will surely benefit us would be a HoC for Radio and Checkboxes. Something like a RadioGroup/CheckGroup. I'm going to close this issue as this specific problem is not related to Galio anymore.
