### ISSUE TITLE
Customizing Galio Theme card

### ISSUE THREAD

**Issue by jizang58** [galio-org/galio#203]
Hi,

I fell in love with the Galio framework it really has beautiful components. I only have one question I wanted to use the card component but it is too big with its default values for my app. So I tried to change the Card_Width in sizes.js and tried to change theme.js but both did not work for me. How can I do it I am pretty much new to React-Native and javascript. Hopefully someone can give me a pointer.

My code:
Card
```
<View>
        <Card
          flex
          
          style={styles.card }
          title={item.name}
          caption="139 minutes ago"
          
          location="Los Angeles, CA"
          avatar="http://i.pravatar.cc/100?id=skater"
          imageStyle={styles.cardImageRadius}
          imageBlockStyle={{ padding: theme.SIZES.BASE / 2 }}
          image="https://images.unsplash.com/photo-1497802176320-541c8e8de98d?&w=1600&h=900&fit=crop&crop=entropy&q=300"
        />
      </View>
```

index.js

 ```
const providerTheme = {
      COLORS: { ...GalioTheme.COLORS, ...CUSTOM_COLORS },
      SIZES: { ...GalioTheme.SIZES, ...CUSTOM_SIZES },
      CARD_WIDTH: 10/5,

      ...customTheme
    };
```

sizes.js
 ```
 BASE: 10  instead of 16.
  CARD_WIDTH: width - (10 * 2),

```

**Comment by AndyOsei** [comment]
@jizang58 You dont have to override the theme just for the CARD_WIDTH unless you want to define default sizes, colors you wanna reuse across your app..

To achieve your desired effect, you can remove the flex prop from the card and pass ‘’’style={{ width, height }}’’’ to override the width and height of the card...

**Comment by palingheorghe** [comment]
Will close the issue as Andy replied with a good advice.
