### ISSUE TITLE
Input multiline textverticalalign on top doesnt work

### ISSUE THREAD

**Issue by davStar** [galio-org/galio#208]
**Describe the bug**
I ve encountered an issue concerning Input using multiline. 
The multiline is well integrated however when I ve tried to align the text on top nothing happen.
![image](https://user-images.githubusercontent.com/26174579/83915572-d089f080-a773-11ea-8848-af96289005d1.png)

**To Reproduce**
Here bellow the code for Input integration:

`                <Input  multiline={true} placeholder="Décriver votre demande ..." color={theme.COLORS.THEME} style={{textAlignVertical:'top', borderColor: theme.COLORS.THEME, height: 100, width: '80%' }} placeholderTextColor={theme.COLORS.THEME}/>
`

**Expected behavior**
The result should be this one:

![image](https://user-images.githubusercontent.com/26174579/83916170-fcf23c80-a774-11ea-9cfe-94df98d2db15.png)

**Screenshots**

**Smartphone (please complete the following information):**
Simulated on IOS platform.

**Comment by AndyOsei** [comment]
@devStar, passing the justifyContent, alignItem style props should solve the problem...check the snippet below for usage...

```
<Input
        multiline
        placeholder="Décriver votre demande ..." 
        color="red" 
        style={{
          justifyContent: "flex-start",
         alignItems: "flex-start",
          textAlignVertical:'top', 
          borderColor: 'black', 
          height: 100, 
          width: '80%' 
        }}
/>
```
