### ISSUE TITLE
color options for showPass icon and help text for the input

### ISSUE THREAD

**Issue by Ace000001** [galio-org/galio#213]
Galio is a great UI library, I love it so far! But there is a scenario in my app where i don't want to use the the default black color of showPass icon and help text in the input(I want these in white).
![image](https://user-images.githubusercontent.com/11032498/85393299-32b16680-b566-11ea-829e-732b593acf6e.png)

I have been looking for the props of input component in the documentation but i couldn't find anything on that in the documentation. So I wasn't able to find a way to achieve this using Galio.

If there is a way please let me know. Otherwise it would be nice to provide more props to control the styling of these elements.

**Comment by EtainLove** [comment]
You can do like this:

```javascript
                <Input
                  ...
                  help={
                    this.state.available ? (
                      <Text style={{ color: "orange" }}>
                        {this.state.message}
                      </Text>
                    ) : (
                      <Text style={{ color: "red" }}>{this.state.message}</Text>
                    )
                  }
                  bottomHelp
                 ...
```

**Comment by Ace000001** [comment]
@EtainLove  any solution for the icon color?

**Comment by EtainLove** [comment]
It is easy. You need to set iconColor to white

Here is how I did:

```
<Input
 password
 viewPass
 color="white"
 iconColor="white"
 ...
/>
```

**Comment by Ace000001** [comment]
awesome! it worked thanks.
