### ISSUE TITLE
Unable to resolve module `./Text`

### ISSUE THREAD

**Issue by william-levi** [galio-org/galio#217]
**Describe the bug**
i guess Text was removed
**To Reproduce**
1. install galio-framework 
2. run your app
3. See error

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - Type of device: [e.g physical/simulator]
 - React-Native version: [e.g. 0.57]
 - Expo version: [e.g. 2.9.0]

**Additional context**

**Comment by AndyOsei** [comment]
@william-levi it has been fixed in the 0.7.1 release...kindly check it out...
