### ISSUE TITLE
How to integrate as a UI component library

### ISSUE THREAD

**Issue by antelbra** [galio-org/galio#32]
Hi! I'd like to know how can I import Galio as would do with other component libraries (NativeBase/ui-kitten), if it is possible.

Thank you! It looks amazing 🤩

**Comment by hetmann** [comment]
@antelbra you can use galio-framework npm package from: https://www.npmjs.com/package/galio-framework

Just install it using npm or yarn
`npm install galio-framework` or `yarn install galio-framework`

**Comment by hetmann** [comment]
@antelbra We've updated the README doc with SDK instructions.

**Comment by antelbra** [comment]
Oh thanks! I’ve been searching on the npm list with “galio” but it didn’t show me anything.

**Comment by hetmann** [comment]
Hmmm, I just searched `galio` and found it: https://www.npmjs.com/search?q=galio
Anyways, let us know your opinion and any features missing 👍
