### ISSUE TITLE
Theme variables instead of calculations in components

### ISSUE THREAD

**Issue by paullaros** [galio-org/galio#36]
https://github.com/galio-org/galio/blob/0b9d8583efe05a1b68e8cbcc6df01b13afffa7b7/src/Block.js#L137-L138

Creating a border radius variable would be much cleaner as you can re-use it in other components instead of doing the calculation inside the component.

**Comment by hetmann** [comment]
@paullaros Good idea, we'll restructuring the variables when we're adding the themeable feature to the kit.

**Comment by hetmann** [comment]
@paullaros @palingheorghe done in galio-framework@1.1.0
