### ISSUE TITLE
Theme & Colors

### ISSUE THREAD

**Issue by paullaros** [galio-org/galio#37]
https://github.com/galio-org/galio/blob/0b9d8583efe05a1b68e8cbcc6df01b13afffa7b7/src/theme.js#L1-L22

Separating theme from colors would be much cleaner. Or create multiple sections like:

Theme: primary, secondary, success, warning, danger
Colors: white, black, grey, blue, red, etc
Social: dribbble, github, etc

**Comment by hetmann** [comment]
@paullaros @palingheorghe done in galio-framework@1.1.0

**Comment by dheerajvora** [comment]
TS2532: Object is possibly 'undefined'.

theme.COLORS.FACEBOOK,
