### ISSUE TITLE
Custom Theme Constants

### ISSUE THREAD

**Issue by vativa** [galio-org/galio#39]
It would be nice to provide a way to overwrite/customize the theme constants from a project location like .galio/theme.js for example, and of course if not found, then load the default theme.js file that came with the release.

`const COLORS = {`
&nbsp;&nbsp;&nbsp;&nbsp;`WHITE: '#FFFFFF',`
&nbsp;&nbsp;&nbsp;&nbsp;`BLACK: '#000000',`
&nbsp;&nbsp;&nbsp;&nbsp;`GREY: 'custom',`
&nbsp;&nbsp;&nbsp;&nbsp;`THEME: 'custom',`
&nbsp;&nbsp;&nbsp;&nbsp;`PRIMARY: 'custom',`
&nbsp;&nbsp;&nbsp;&nbsp;`INFO: 'custom',`
&nbsp;&nbsp;&nbsp;&nbsp;`ERROR: 'custom',`
&nbsp;&nbsp;&nbsp;&nbsp;`WARNING: 'custom',`
&nbsp;&nbsp;&nbsp;&nbsp;`SUCCESS: 'custom',`
&nbsp;&nbsp;&nbsp;&nbsp;`...`

**Comment by hetmann** [comment]
@vativa We're working on a feature to create a themeable option included on the kit. Stay tuned for updates.
Until then you can use the props for each component to customise it, e.g.: color, bgColor, etc.

**Comment by hetmann** [comment]
@vativa @paullaros @palingheorghe done in galio-framework@1.1.0

**Comment by hetmann** [comment]
@vativa take a look at this doc: https://github.com/galio-org/galio/blob/theme/src/theme/README.md
