### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by antelbra** [galio-org/galio#40]
Hi! If you like I could do the Spanish translation of the Docs and the README. If you agree, tell me how would you like to make the pull request ✌️

**Comment by palingheorghe** [comment]
Hi @antelbra, 

Of course we would love to have this translated ❤️. You can find our docs [here](https://github.com/galio-org/docs). 

I'm not sure how Docsify works with multi-language support, I will look into this. Being the fact that our documentation isn't really that big right now, we could always move to a different static site/docs generator if we would have to. 

🤙🏽

**Comment by palingheorghe** [comment]
### New info: 

So... I've updated the [docs repo](https://github.com/galio-org/docs) with a `_navbar.md` file for all translations. You just need to fork the [repo](https://github.com/galio-org/docs), create a new branch and edit the [README.md](https://github.com/galio-org/docs/blob/master/es/README.md) file inside the [es/ folder](https://github.com/galio-org/docs/tree/master/es).

Thanks for your interest in helping our cool project. ❤️

**Comment by antelbra** [comment]
Great! ✌️
