### ISSUE TITLE
Can't create project as in documentation

### ISSUE THREAD

**Issue by antelbra** [galio-org/galio#46]
**Describe the bug**
When I try to install the project as in the documentation, with the steps provided. The main error that I get is "missing script: ios". I only tried with ios, but I would get the same error because there isn't android script neither.

**To Reproduce**
1. Clone the repository
2. Get into the project folder
3. run "npm install" or "yarn install". It doesn't matter which manager I use.
4. Run "npm run ios"

Steps to reproduce the behavior with Expo:
1. Clone the repository
2. Get into the project folder
3. run "npm install" or "yarn install". It doesn't matter which manager I use.
4. Run "expo start"

**Expected behavior**
The project should open as expected with Expo.

**Screenshots**
![image](https://user-images.githubusercontent.com/16032649/47847095-1a556c80-ddc2-11e8-82b6-77c1ce2ba5fe.png)

![image](https://user-images.githubusercontent.com/16032649/47847125-31945a00-ddc2-11e8-940f-e92241b10e14.png)

**Computer (please complete the following information):**
 - Device: MacBook Pro 2016
 - OS: macOS Mojave
- Node version: 10.13.0
- Expo version: 2.2.5

**Additional context**
I don't know why Im getting this problem now, because one week ago I could run the project as expected with Expo.

**Comment by palingheorghe** [comment]
Hi @antelbra,

Sorry for the late response. You're on the `master` branch. In order to be able to check out the RN app, you'll need to open up your terminal and inside Galio's folder write `git checkout examples`. Now make sure you're up to date with our repo and then run `npm install` or `yarn install`. It should work. 

Thanks! 🤙🏽

**Comment by antelbra** [comment]
@palingheorghe Works perfectly! Thank you ✌️

**Comment by palingheorghe** [comment]
@antelbra no problem!
