### ISSUE TITLE
Custom Component Names

### ISSUE THREAD

**Issue by antelbra** [galio-org/galio#47]
**Is your feature request related to a problem? Please describe.**
When I have to use components from different libraries I have to handle the problem with common name between them.

**Describe the solution you'd like**
I think it would be great to have the components from Galio with an identifier that make them easily recognizable from the other. For example, to use the prefix "Ga":
```javascript
import { Button, Text } from 'react' // Default components
import { GaButton, GaBlock, GaText } from 'galio-framework' // Awesome Galio Components
```

**Describe alternatives you've considered**
I didn't think about another aproach but I'd like to now your opinions and if you have already an alternative for this.

**Additional context**
I've seen this methodology in the "Kitten Component Kit". They do it this way:
```javascript
import { Button, Text } from 'react' // Default components
import { RkButton } from 'react-native-ui-kitten' // Kitten Components
```

**Comment by antelbra** [comment]
@hutmann I think that it could be great to give galio components more personality and identity when using with other UI libraries. Also, is less verbose that way, I think.

What are your thoughts?

**Comment by hetmann** [comment]
@antelbra You're right, I like the "personality & identity" idea :)
In the next update we'll add this one.

**Comment by antelbra** [comment]
@hetmann I can help with that if you want ✌️

**Comment by palingheorghe** [comment]
Closed the issue after discussing this on our [Gitter](https://gitter.im/galio-community/Lobby) channel.
