### ISSUE TITLE
The screen "Order Confirmed" don't show left panel.

### ISSUE THREAD

**Issue by antelbra** [galio-org/galio#50]
**Describe the bug**
In the "Order Confirmed" screen there is a minor error when trying to open the left panel due to props handling, showing "variable props not found".

**To Reproduce**
1. Run the project in the examples branch
2. Open the screen "Order Confirmed"
3. Try to open the left panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/16032649/47964347-a1a81780-e030-11e8-8be1-4763f52cb3c0.png)

**Expected behavior**
The left panel should be opened as in the other screens.

**Additional context**
I already fixed the error and I'm going to make a pull request.

**Comment by palingheorghe** [comment]
Hi @antelbra ,

Thanks for finding out about this bug! I've merged your PR to the `examples` branch!

🤙🏽
