### ISSUE TITLE
Working without Expo SDK

### ISSUE THREAD

**Issue by Taimoormk** [galio-org/galio#55]
Ideally, I prefer to work without Expo SDK. I happen to like your components library and wanted to give them a shot, but found out Expo SDK is required to make this work, is that so or have I overlooked a step to use this library without Expo? It would be great to see this work as standalone if possible.

**Comment by hetmann** [comment]
@Taimoormk all the components have non-expo dependencies, only the **Icon** component has the expo dependency.
We are working on to make the Galio expo free.

**Comment by Taimoormk** [comment]
@hetmann Thank you for the update.

Yeah it would be great to be Expo free but it sure has added to my knowledge that all components are currently Expo free except the Icon one. Great work.

**Comment by avinashvalluru** [comment]
@hetmann may i know when can i expect icon without expo sdk ?

**Comment by palingheorghe** [comment]
Hi @avinashvalluru , 
We can't give out a specific ETA for this. We're planning on releasing Galio without the Expo SDK in version 0.6. 

Thanks, 
Alin 🤙🏽

**Comment by abdulmalek-albakkar** [comment]
@palingheorghe  any update on this?

**Comment by AndyOsei** [comment]
You can currently use Galio without Expo which i have done a couple of times in a few projects...
Just install react-native-vector-icons in your project so you can use the Icon component without any problems.

You can let me know if you face any issues doing so...
