### ISSUE TITLE
Components: Custom from inputs (checkbox, radio)

### ISSUE THREAD

**Issue by palingheorghe** [galio-org/galio#57]
**Read this:** [Working on a PR](https://github.com/galio-org/galio/wiki/Working-on-a-PR) | [CONTRIBUTING](https://github.com/galio-org/galio/blob/master/CONTRIBUTING.md) | [Galio's docs](https://galio.io/docs/)

As I've written in our [wiki](https://github.com/galio-org/galio/wiki). We're working towards v0.5 and for this thing to happen we need the following components.

Do you want to **help**? Just comment which of the following components you wish to work on: 
- [x] Radio Button  _**(TAKEN BY @samcyn)**_
- [x] Checkbox **_(TAKEN BY @palingheorghe)_**

**Design** files for: [Check box](https://github.com/galio-org/galio/tree/design/v0.5%20components/Checkbox) | [Radio Button](https://github.com/galio-org/galio/tree/design/v0.5%20components/Radio)

🤙🏽

**Comment by samcyn** [comment]
Hi @palingheorghe I'll like to work on the radio component.

**Comment by palingheorghe** [comment]
Cool! I've assigned you this task! @samcyn 
Galio's community is awesome! If you have any questions don't forget to contact us here or on [Gitter](https://gitter.im/galio-community) ❤️!

🤙🏽

**Comment by palingheorghe** [comment]
Hi @samcyn, 
Are you still available to create the radio component? 

Thanks ❤️

**Comment by samcyn** [comment]
Yes very well. Had a long break and just resuming. Should be done in a week. Thanks

On Feb 12, 2019 11:15 AM, Petru Alin Gheorghe <notifications@github.com> wrote:

Hi @samcyn<https://github.com/samcyn>,
Are you still available to create the radio component?

Thanks ❤️

**Comment by palingheorghe** [comment]
Hi @samcyn, 
We needed this component for releasing v0.5 of Galio, could you please give us an ETA? 

Thank you for your help,
Alin 🤙🏽

**Comment by samcyn** [comment]
hi sorry for the delay I change job and location, and my new place has been demanding. Expect a pull request tonight anyways. Regards. Samson
________________________________
