### ISSUE TITLE
Components: Switch

### ISSUE THREAD

**Issue by palingheorghe** [galio-org/galio#60]
**Read this:** [Working on a PR](https://github.com/galio-org/galio/wiki/Working-on-a-PR) | [CONTRIBUTING](https://github.com/galio-org/galio/blob/master/CONTRIBUTING.md) | [Galio's docs](https://galio.io/docs/)

As I've written in our [wiki](https://github.com/galio-org/galio/wiki). We're working towards v0.5 and for this thing to happen we need the following component.

Do you want to **help**? Just comment if you wish to work on: 
- [x] Switch _**(TAKEN BY @antelbra)**_

**Design** files for: [Switch](https://github.com/galio-org/galio/tree/design/v0.5%20components/Switch)

🤙🏽

**Comment by antelbra** [comment]
Hi @palingheorghe ! I'd like to work on the Switch creation ✌️

**Comment by palingheorghe** [comment]
Hi @antelbra! Cool, I've assigned you this one! 

🤙🏽
