### ISSUE TITLE
Screens: Segment Screen/Settings Screen

### ISSUE THREAD

**Issue by palingheorghe** [galio-org/galio#61]
**Read this:** [Working on a PR](https://github.com/galio-org/galio/wiki/Working-on-a-PR) | [CONTRIBUTING](https://github.com/galio-org/galio/blob/master/CONTRIBUTING.md) | [Galio's docs](https://galio.io/docs/)

As I've written in our [wiki](https://github.com/galio-org/galio/wiki). We're working towards v0.5 and for this thing to happen we need the following screens.

Do you want to **help**? Just comment if you wish to work on: 
- [ ] Segment Screen ( 01A/01B )
_This screen uses the Segment and Slider components (#58 && #59 )_
- [ ] Settings Screen (02)
_This screen uses the Radio, Check Box and Switch components (#57 && #60)_

**Design** files for [Screens -- both of them are in the same file](https://github.com/galio-org/galio/tree/design/v0.5%20components/screens)

🤙🏽

**Comment by shubhamkakkar** [comment]
Segment screen is added !!

**Comment by camilogiraldo** [comment]
Hey, I just want to get involved in this. Can I help with either of those screens ?

**Comment by palingheorghe** [comment]
Hi @camilogiraldo ! Yes of course you can get involved, we can't really do the Segment screen right now but you can do the Settings screen. 

🧜🏽‍♂️

**Comment by tkalejaiye** [comment]
Is this still open to work on? I can see from #127 that some work has already been done on at least one of these screens.

**Comment by palingheorghe** [comment]
Hi @tkalejaiye! The Settings screen has been already created and we don't have the Segment component included in Galio yet so this issue should be suspended until we got the other component! But thank you for wanting to help, we always need a hand around here!

**Comment by palingheorghe** [comment]
Moved the galio-app to another repo called [galio-starter-kit](https://github.com/galio-org/galio-starter-kit). So all the issues regarding the app need to move there as well. Thank you! 🧜🏽‍♂️
