### ISSUE TITLE
Change Syntax: Import and Export Components

### ISSUE THREAD

**Issue by antelbra** [galio-org/galio#63]
**Is your feature request related to a problem? Please describe.**
Change the syntax to import and export Components.

**Describe the solution you'd like**
```javascript
// Import and Export in the same line
export { Block } from './Block';
export { Button } from './Button';
export { Card } from './Card';
export { Icon } from './Icon';
export { Input } from './Input';
export { NavBar } from './NavBar';
export { Text } from './Text';
export { Switch } from './Switch';
export theme, { withGalio, GalioProvider } from './theme';
```
Instead of this:
```javascript
import Block from './Block';
import Button from './Button';
import Card from './Card';
import Icon from './Icon';
import Input from './Input';
import NavBar from './NavBar';
import Text from './Text';
import theme from './theme';

export {
  Block,
  Button,
  Card,
  Icon,
  Input,
  NavBar,
  Text,
  theme,
};
```

**Describe alternatives you've considered**
Leave it as it's now

**Comment by palingheorghe** [comment]
In my opinion, there's nothing wrong with the way things are written now in the `index.js` file.
I think we'll leave it as it is for now and if more issues like this one emerge than we're going to direct people to this issue. 

Alin 🤙🏽
