### ISSUE TITLE
instructions don't work for expo client on ios

### ISSUE THREAD

**Issue by Morriz** [galio-org/galio#65]
There is no such thing as "typing into the Expo Client". Please provide proper clickable link to allow your demo app to open in Expo Client for iOS.

**Comment by Morriz** [comment]
Nah, it was described by the expo team on their blog that on iOS only your own projects are loading, 3rd party apps are not allowed:

![img_1350](https://user-images.githubusercontent.com/941865/49170125-c051b380-f33b-11e8-8bb6-b747abecfbef.png)

**Comment by Morriz** [comment]
The info should reflect that...

**Comment by Morriz** [comment]
https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a

**Comment by hetmann** [comment]
@Morriz sorry for that, @palingheorghe can you update the docs as Morriz mentioned it?

**Comment by palingheorghe** [comment]
Hi @Morriz ! 
Could you please tell me where is it written 'typing into the Expo Client'? You can open our app with Expo either on your physical device or your simulator by forking the repo, entering the 'examples' branch and writing `expo start`. This will open up an Expo server which will allow you to check out our app on iOS Expo. 

You're right, we haven't been very clear regarding instructions for iOS. We'll write that in our README and Wiki.

Thanks for the issue! 

🤙🏽

**Comment by pherm** [comment]
I have some problems

**Comment by palingheorghe** [comment]
Hi @pherm, 

Are you talking about testing on iOS? Unfortunately, Expo doesn't support testing other people's apps on iOS anymore. You can only test the app using the QR code or [this link](https://expo.io/@galio-framework/galio-native-kit) on Android. This is not a Galio related issue, it is more a limitation issue Apple has imposed on apps like Expo. 

You can always test our app on iOS by cloning the repo and creating a localhost server for you to install and check out our project through a physical device or a simulator. 

Thanks!
