### ISSUE TITLE
not start project? npm run android / npm run ios not working!

### ISSUE THREAD

**Issue by leommh** [galio-org/galio#70]
Hi, sorry for the inconvenience and my English. My native language is not English, so maybe some things go wrong.

But I would like to report that I cloned the project, I installed it with npm install, but no command worked to run the project on my android emulator. I looked in the package and it does not seem to have any script to start the project. And even installing the expo, I also could not start it.

I wonder if it's really bugged, or if it's me that I'm doing wrong. Because I would like to test and who can help improve the library.

I thank you for your attention :)

**Comment by palingheorghe** [comment]
Hi @leommh, 

If you'd like to test Galio (check out some of its screens, components, etc) you need to install the `examples` branch, **not** the `master` branch which only contains the components ready to be used in your app. 

If you'd like to use Galio in your app then you'd want to create a new Expo app and then run `npm install galio-framework`. After that, you'd be able to use Galio just like any other library. 
 
Example: 
Let's say you want to use Galio's Buttons inside your `App.js` (your app's entry point). You'd be importing the Button like this: `import { Button } from 'galio-framework';` and then inside a `<View />` block of code you'd write `<Button>My button</Button>`.

Most of this information is right on our website/docs: [galio.io](https://galio.io) or [galio.io/docs](https://galio.io/docs).

You can also ask questions on our Gitter: [https://gitter.im/galio-community](https://gitter.im/galio-community).

Thanks,
Alin 🤙🏽
