### ISSUE TITLE
Focus() in Input!

### ISSUE THREAD

**Issue by leommh** [galio-org/galio#74]
**Is your feature request related to a problem? Please describe.**
The inputs do not pass the functions of focus (), blur (), among others of the TextInput of React Native.

**Describe the solution you'd like**
I would like these functions to be passed so that I could control focus and transfer from one input to another after I finish entering the value.

**Describe alternatives you've considered**
When the line:
ref = {input => (this.input = input)}
is added to the TextInput automatically the Input class wins the properties.

When creating the function:
function focusOnTextInput () {
    return this.input.focus ()
};
It automatically causes the input to be focused, if it were to pass that function forward when the Input was imported, it was just to use it and the input would be focused.

But I tried to do this and the input does not show this function in its this, I do not know if it is because of the "withGalio" that is doing something, but the function does not come when using the input.

**Additional context**
Here is an example I could do by creating a customizable TextInput of mine!

![1](https://user-images.githubusercontent.com/10534281/53572143-523ea780-3b49-11e9-824c-688da646b799.jpg)

![2](https://user-images.githubusercontent.com/10534281/53572147-579bf200-3b49-11e9-93ff-540cd6fb9969.jpg)

**Comment by iamshrikantjha** [comment]
Image 1
![whatsapp image 2019-03-02 at 12 34 16 am](https://user-images.githubusercontent.com/22591983/53660055-055eec00-3c83-11e9-86bc-23efa7eaa9b5.jpeg)
Image 2

![whatsapp image 2019-03-02 at 12 34 11 am](https://user-images.githubusercontent.com/22591983/53660052-04c65580-3c83-11e9-980c-b05738b757b0.jpeg)


When we are using expo application then in Login Screen option there is an issue with input.
Sorry I am not very much experienced but can I try to fix this?

**Comment by iamshrikantjha** [comment]
![whatsapp image 2019-03-02 at 12 40 16 am](https://user-images.githubusercontent.com/22591983/53660451-ec0a6f80-3c83-11e9-8bd8-c7620d9b1145.jpeg)
Same issue with register screen

**Comment by leommh** [comment]
Man, since it's an open library, I think you can try to sort and upload a pull request here in the project.

To try to give you a help and believe that this is happening because of the "KeyboardAvoidingView", this component has a property called keyboardVerticalOffset that defines how much effect it will apply when the input is selected.

Doc Official: https://facebook.github.io/react-native/docs/keyboardavoidingview

**Comment by hetmann** [comment]
@leommh maybe you can try using: https://reactjs.org/docs/forwarding-refs.html

**Comment by sam1463** [comment]
Another option, much like ref forwarding, but that would allow refs to either the galio input or the react-native textinput, would be to just add an `onRef` (or otherwise named) prop to the galio input component, which is then just passed to the text input.

```
// when you render the galio component
<Input
    onRef={input => { this.input = input }}
    ....
/>
```

```
// proposed changes to the galio component (in render method)
<TextInput
            ref={this.props.onRef} // passes the ref fn on to the text input
            style={inputStyles}
            keyboardType={type}
            secureTextEntry={isPassword}
            placeholderTextColor={placeholderTextColor}
            underlineColorAndroid="transparent"
            {...props}
          />
```

If that would be ok, I can open a PR. I've just changed it locally and it's working

**Comment by palingheorghe** [comment]
@sam1463 's solution is now included in v0.6 

Thanks for your help!

**Comment by initzx** [comment]
Hello, is there an example of how to get galio working with focus(). It doesn't seem to work for me, when i set onRef on the input i wish to focus on

**Comment by sam1463** [comment]
@initzx It should work to use it like this:

```
// in method where you want to focus on the input
this.input.focus();

...

// in render method
return (
  ...other stuff
  <Input
    onRef={(ref) => { this.input = ref; }}
    ...other input props
  />
  ...more stuff
);
```

**Comment by palingheorghe** [comment]
Thank you for explaining @sam1463 ! Just noticed the new Input misses that prop so it might not work. This needs to be updated asap so I'll reopen the issue.

**Comment by sam1463** [comment]
@palingheorghe oh yeah good catch! It looks like in this commit when that component was changed from a class component to a functional one, the `onRef` prop got removed, probably just a bad merge resolution since that prop had only just barely made it into the repo before that.
https://github.com/galio-org/galio/commit/e48774276d92e88e75a62df64378ec277df15a6d

**Comment by palingheorghe** [comment]
You think you can push another PR for this issue? @sam1463

**Comment by sam1463** [comment]
Yep, fixed it locally last night but haven't had time to open a PR yet. I should be able to when I get home later today.

**Comment by palingheorghe** [comment]
Thank you for your help! Looking forward to the PR!

**Comment by ammar-sheikh** [comment]
hey @sam1463
kindly can you push the PR!

**Comment by sam1463** [comment]
I already created one. For me, it's linked right above your comment, but in case that's not visible to you for some reason, it's here: https://github.com/galio-org/galio/pull/145

**Comment by palingheorghe** [comment]
Hi @ammar-sheikh ! I'll push the PR to the master server as soon as possible, I'm just trying to collect more PRs because some developers already invested into a workaround for lots of bugs we had so any new version could break their apps.

**Comment by gamingumar** [comment]
When the merge is expected?

**Comment by palingheorghe** [comment]
@gamingumar next week we'll clean the repo so we'll merge this PR as well because we're getting ready for v1.0.

**Comment by shiroze** [comment]
> @initzx It should work to use it like this:
> 
> ```
> // in method where you want to focus on the input
> this.input.focus();
> 
> ...
> 
> // in render method
> return (
>   ...other stuff
>   <Input
>     onRef={(ref) => { this.input = ref; }}
>     ...other input props
>   />
>   ...more stuff
> );
> ```

I try using like this but give me null is not an object Package.json (v.0.6.3)

**Comment by palingheorghe** [comment]
Closed because we've merged the PR into the `dev` branch. Thank you!
