### ISSUE TITLE
Spanish translation docs

### ISSUE THREAD

**Issue by palingheorghe** [galio-org/galio#77]
Hi guys! 

As you can see we've added the last 4 new components to our documentation. We need help translating the new pages into Spanish (because we already have the spanish translation which is now outdated with our new update). 

Last time @antelbra did the translation. So if he is able to help us again that'd be great but if he's not available and someone wants this issue that'd be fine as well. 

You can find our docs [here](https://github.com/galio-org/docs).

Thanks,
Alin

**Comment by antelbra** [comment]
I'll do it ✌️ @palingheorghe

**Comment by palingheorghe** [comment]
That's great! Thanks for all the help! ❤️
