### ISSUE TITLE
Unable module expo on react native init

### ISSUE THREAD

**Issue by nicoaudy** [galio-org/galio#80]
**Bug**
Error: Unable to resolve module `expo` from `path/appname/node_modules/galio-framework/src/Icon.js`: Module `expo` does not exist in the Haste module map.
im using react-native init instead of expo, any suggestion?

**Comment by palingheorghe** [comment]
Hi @nicoaudy ! 

Galio had dependencies in Expo so you will need to have Expo installed in order to use our library.

Thanks 🤙🏽
