### ISSUE TITLE
Doesn't work on expo 32 with typescript

### ISSUE THREAD

**Issue by dantopa** [galio-org/galio#81]
When trying to use a component says:

undefined is not an object (evaluating '_reactNativeVectorIcons.default.Galio = 0, _reactNativeVectorIcons.createIconSetFromIcoMoon)(_galio.default, 'Galio')')

**Comment by palingheorghe** [comment]
Hi @dantopa !

I will need more details on this, I'm not sure what's the issue, could you expand on this a bit more, please? What component did you import? Is it a new project? What's your react native version? We have a bug/question issue template that you can use 😊.

Thanks 🤙🏽

**Comment by pejoujarrar** [comment]
I have the same problem, any updates?

**Comment by palingheorghe** [comment]
Hi @pejoujarrar ! The latest version should work with Expo 33/32. I haven't added any support for typescript yet. If any of you would like to help out with this that'd be great! ⭐️

**Comment by leslielyj** [comment]
@palingheorghe Have the same issue, worked perfectly fine before I upgraded to SDK 33. 
Error Message:
`
Uncaught Error: undefined is not an object (evaluating 'S.default.Galio=(0,S.createIconSetFromIcoMoon)(w.default,'Galio')')`


before: 
```
"expo": "^32.0.0",
"galio-framework": "^0.5.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",

```
after
```
"expo": "^33.0.0",
"galio-framework": "^0.5.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
```

**Comment by pejoujarrar** [comment]
> Hi @pejoujarrar ! The latest version should work with Expo 33/32.

Hi @palingheorghe, it works fine with 32 but not with the version 33. The error above appears with this version.

**Comment by palingheorghe** [comment]
Hi @leslielyj @pejoujarrar ! Have you tried upgrading `galio-framework`? Our latest version `0.5.3` works perfectly fine with SDK33. I've removed Expo completely so there shouldn't be any more problems with Expo from now on. 

Thanks, Alin 🤙🏽
