### ISSUE TITLE
Slider ReferenceError: Can't find variable: style

### ISSUE THREAD

**Issue by ghasemikasra39** [galio-org/galio#82]
I'm trying to use Slider:
```js
import { Slider } from 'galio-framework'
import React, { Component } from 'react';
import { View } from 'react-native';
export default class GalioPresentation extends Component {
    render() {
        return (
            <View>
                <Slider />
            </View>
        );
    }
}
```
I get the error:

> ReferenceError: ReferenceError: Can't find variable: style
 This error is located at:
in Slider (at theme/index.js:33)
in _class (at GalioPresentation.js:8)
 in RCTView (at View.js:44)
 in GalioPresentation (at LightingPresentation.js:179)
 in RCTView (at View.js:44)
 in RCTView (at View.js:44)

**Comment by hetmann** [comment]
@ghasemikasra39 good finding, it is a small typo.

Destructuring **styles** from this.props `const { minimumValue, maximumValue, trackStyle, thumbStyle, activeColor, disabled, theme, styles } = this.props;`
Link: https://github.com/galio-org/galio/blob/master/src/Slider.js#L127

-> `const containerStyles = [styles.container, style];`
Link: https://github.com/galio-org/galio/blob/master/src/Slider.js#L150

**Comment by palingheorghe** [comment]
Merged your PR! Thank you very much for your work! It's already on the master branch + some other changes. If you want to know more about v0.5.2 please read the release notes [here](https://github.com/galio-org/galio/releases/tag/v0.5.2).

Thanks, Alin.
