### ISSUE TITLE
Icon detailed how to

### ISSUE THREAD

**Issue by superandrew** [galio-org/galio#85]
**Is your feature request related to a problem? Please describe.**

I'm sure this is related to my deep ignorance on the subject, however, I think that some explanation on how to use icons could be of help to many who, like me, don't understand how to display an icon.

**Describe the solution you'd like**

I think that a link and an example of how to use an icon name to display an icon would be of great help.

**Describe alternatives you've considered**

On the documentation is reported that the expo vector icon list is supported. So I thought that by using the name of one of those icons would be allowed. I tried many, to no avail.

However, probably that's not the right solution. I found in the npm package that there is a galio.json which maps the icons with their names, so probably every available icon name is there, even if it seems a bit uncomfortable to dig.

**Additional context**

I would like to contribute to the documentation if instructions are provided to me so that I understand how to display an icon and which is the list to choose from.

**Comment by superandrew** [comment]
here's the list I created using the provided `json` file

```
for (var i in icons){
	const name = icons[i].properties.name!==undefined?icons[i].properties.name:""
	console.log(`${name}`)
}
```

```
zoom-split-out
zoom-split-in
volume-97
volume-93
users-ww
users-ww-2
users-wm
users-wm-2
users-mm
users-mm-2
ui-04
ui-03
trash-simple
towel
thumb-up
thumb-down
telegram
tail-up
tail-right
tail-left
tail-down
support-17
stre-up
stre-right
stre-left
stre-down
smile
small-up
small-right
small-left
small-down
single-folded
single-folded-content
single-copy-04
single-copies
single-content-03
single-content-02
single-03
simple-remove
share-bold
settings-gear-63
server-rack
quote
puzzled
notepad
minimal-up
minimal-down
manga-63
list-numbers
img-stack
google
folder-14
flower-06
drag-31
currency-yen
currency-pound
currency-euro
currency-dollar
copy-2
circle-08
check-square-11
check-square-09
check-single
check-circle-08
check-circle-07
check-2
chat-round
chat-46
chat-45
chart-pie-36
chart-pie-35
chart-growth
chart-bar
certificate
button-stop
button-skip
button-rewind
button-record
button-play
button-pause
button-next
brightness
box
bag
badge
archive-paper
archive-content
align-right
align-left
align-justify
align-center
eye
add-27
analytics
bag-17
credit-card
eye-17
grid-48
grid-square
heart-2
list-bullet
log-in
log-out
minimal-left
minimal-right
paper-2
pin-3
preferences-circle-rotate
presentation
segmentation
selection
settings-gear-65
single-paragraph
tablet-reader-31
zoom-split
```

It would be very useful to have this list on the documentation, with the icon on the side, wouldn't it?

**Comment by palingheorghe** [comment]
Hi @superandrew, 
As you can see on https://galio.io/docs/#/components/icon there's an example from which you can take inspiration. If you want to use any Icon that Expo has (https://expo.github.io/vector-icons/ ) you need to use it as following: `<Icon name="EXPO-ICON-NAME" family="EXPO-FAMILY-NAME" color={rgb(100,120,40)} size={10} />`where EXPO-ICON-NAME and EXPO-FAMILY-NAME are taken from the website I've posted above. 

You're right! It would be very useful to have that list. You could totally try and make a PR on our docs repo (https://github.com/galio-org/docs). Just go ahead, fork the repo make your changes and submit a PR. 

Thanks,
Alin 🤙🏽

**Comment by superandrew** [comment]
@palingheorghe ok, I finally got that. I'm honestly learning React, so I might have guessed it, but I didn't get the `family` part. If it is ok, instead of putting the entire icon list, I would integrate with your explanation the Icon section of the documentation. What do you think?

**Comment by palingheorghe** [comment]
Any type of help regarding the documentation and our library is welcomed! Go ahead and submit a PR with your changes! ❤️

Thanks,
Alin 🤙🏽
