### ISSUE TITLE
Components: Toast notification

### ISSUE THREAD

**Issue by palingheorghe** [galio-org/galio#86]
**Read this:** [Working on a PR](https://github.com/galio-org/galio/wiki/Working-on-a-PR) | [CONTRIBUTING](https://github.com/galio-org/galio/blob/master/CONTRIBUTING.md) | [Galio's docs](https://galio.io/docs/)

As I've written in our [wiki](https://github.com/galio-org/galio/wiki). We're working towards v0.6 and for this thing to happen we need the following components.

Do you want to **help**? Just comment if you wish to work on: 
- [ ] Toast Notification **_(TAKEN BY @extenss)_**

If anybody has questions please comment them below. 

🤙🏽

**Comment by extenss** [comment]
Hi, I can take this.

**Comment by palingheorghe** [comment]
Hi @extenss ! Cool, I've assigned you the issue! 

Thanks,
Alin!
