### ISSUE TITLE
Components: Deck Swiper

### ISSUE THREAD

**Issue by palingheorghe** [galio-org/galio#87]
**Read this:** [Working on a PR](https://github.com/galio-org/galio/wiki/Working-on-a-PR) | [CONTRIBUTING](https://github.com/galio-org/galio/blob/master/CONTRIBUTING.md) | [Galio's docs](https://galio.io/docs/)

As I've written in our [wiki](https://github.com/galio-org/galio/wiki). We're working towards v0.6 and for this thing to happen we need the following components.

Do you want to **help**? Just comment if you wish to work on: 
- [ ] Deck Swiper

If anybody has questions please comment them below. 

🤙🏽

**Comment by Chojecki** [comment]
Do you mean Tinder like collection view layout? I did something similar in native Swift here: https://apps.apple.com/pl/app/the-idea/id1454724260

I can try to pick it ReactNative. Are there any requirements like "data source should be..." etc ?

**Comment by palingheorghe** [comment]
Hi @Chojecki ! Yeah, Tinder is the best example of this kind of component. It should be a component with the Tinder deck swiping feature which accepts any type of component. So basically if I want 4 Text components to be stacked one on top of the other and I want to swipe them to the left/right in order to get to the next Text component it should work. 
Do you have any ideas about how should we go on about this component? 

Thanks

**Comment by Chojecki** [comment]
@palingheorghe Ye, I guess it could be a Component which takes an array of Components and map them into Stack of animated views wrapper with those components inside. Then all drag and drop logic will go to this animated wrapper. Not perfect as we can't predict the shape of array but should work. I will try to fork the repo and create something

**Comment by shubhamkakkar** [comment]
Is this issue still open?
As I have made a horizontalScroller before and I could raise a PR here for it ?

**Comment by Chojecki** [comment]
@shubhamkakkar sure, you can take it if you want. I just started doing it in functional components with hooks - I can share you gist if you want, but feel free to pick it instead of me. 

mine works like this when we inject just 3 simple Text components into it:
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/20075941/61204032-69db8e80-a6ec-11e9-84dd-7b6a3d59a52b.gif)

**Comment by shubhamkakkar** [comment]
Hey, it would be nice.
Share me the gist
It would be highly beneficial
Thank you

**Comment by Chojecki** [comment]
@shubhamkakkar link to my code: https://gist.github.com/Chojecki/5c76675ef2a2889ae6e360d4d8a35846

**Comment by shubhamkakkar** [comment]
https://codeburst.io/horizontal-scroll-animations-in-react-native-18dac6e9c720

I was thinking something like this, but with better effects and UX
what's your say?
@Chojecki

**Comment by Chojecki** [comment]
Not sure if this is a Deck Swiper as it isn't a "Deck" but just a CollectionView/ListView of elements

No idea. Better ask @palingheorghe

**Comment by shubhamkakkar** [comment]
Yup i can relate to it not being a ideal deck type 

What's your views about https://link.medium.com/FsQ0zwXqlY

**Comment by Chojecki** [comment]
For me its too specific. I can imagine that users will want as much vanilla component as it’s possible to customise it like they want. Like @palingheorghe mentioned, the perfect example is Tinder like deck. But hey, its not mine repo, so do what you consider the best :)

**Comment by shubhamkakkar** [comment]
Haha
I get it,
the reason why I dont like tinder's deck is because once the component is swiped of, it goes out and with no way to retrieve it, its actually the concern
Where as   https://link.medium.com/FsQ0zwXqlY this if given proper work could be a better swiper than others, with proper chance of rechecking our old swiped out  factors

@Chojecki  and @palingheorghe

**Comment by palingheorghe** [comment]
Hi @Chojecki and @shubhamkakkar ! Guys, I'm really happy that these types of conversations are going on in Galio's repo! ❤️

I understand your concern @shubhamkakkar and I like the whole 'component shouldn't disappear' thing. Can't we combine those two ideas? We could have a prop like `intact` which could let the user(the dev using Galio) toggle between a component where the cards disappear  and one where everything re-shuffles as in your example. That's a great point. 

Thanks to both of you for your awesome work so far @Chojecki @shubhamkakkar ! This is really awesome and I love it when great ideas get together. 

What do you think about the `intact` prop?

**Comment by shubhamkakkar** [comment]
intact props sounds cool, I will try  working on that.

In the mean time I was trying to achieve the monzo card animation and I have come to the requriement of using libraries like **react-native-animated and redash**
Is there any limitation on extra libraries or not?

**Comment by palingheorghe** [comment]
@shubhamkakkar sorry for the late reply, I was always trying to avoid more libraries. Do you think we could do this with a lighter library? I know we could add the dependencies in peerDependencies and the user needs to install those only if he's using them. So basically if the user really needs to use the deck swiper I guess he won't mind installing those? 

What do you think about this? Would adding those libraries make Galio slower and heavier?

**Comment by palingheorghe** [comment]
Hi @shubhamkakkar are you still working on this?

**Comment by palingheorghe** [comment]
@shubhamkakkar imma bump this one more time cause I need to know the progress of this component 

thanks ❤️

**Comment by shubhamkakkar** [comment]
I am sorry, I wasn't able to reply on time,
NO, I am not working in this one !!
Sorry for the inconveniences caused!!
