### ISSUE TITLE
NavigationDrawerItems text cutting off

### ISSUE THREAD

**Issue by iamshrikantjha** [galio-org/galio#90]
**Describe the bug**
The Navigation Drawer is chopping off Drawer label in example branch

**To Reproduce**
1. Install project as it is.
2. Open app on expo.
3. Open Navigation Drawer
![WhatsApp Image 2019-06-02 at 3 40 56 PM](https://user-images.githubusercontent.com/22591983/58759790-5b2a8500-854d-11e9-85ce-3f9c0cf58694.jpeg)

**Expected behavior**
It should not chop off the drawer items.
![WhatsApp Image 2019-06-02 at 3 41 01 PM](https://user-images.githubusercontent.com/22591983/58759805-8614d900-854d-11e9-96ba-914787bdf00e.jpeg)

**Comment by iamshrikantjha** [comment]
I can fix it.
Also I am a beginner in Open Source Contribution. I am open to suggestions.

**Comment by palingheorghe** [comment]
Hi @iamshrikantjha ! Thanks for opening this issue! 

Sorry for the late reply, yes you can go ahead and fix it, before that please don't forge tot read the [CONTRIBUTING](https://github.com/galio-org/galio/blob/master/CONTRIBUTING.md) file and [How to open a PR](https://github.com/galio-org/galio/wiki/Working-on-a-PR).

Thanks for your help,
Alin🤙🏽

**Comment by iamshrikantjha** [comment]
How can I fork or make changes to your branch examples?
I am finding it difficult.

**Comment by palingheorghe** [comment]
Hi again @iamshrikantjha! 
There's a Fork button in the top right corner of this page. That will fork the project into your GitHub account. It's kind of like creating a copy of someone else's repository on which you can experiment and do whatever you want. Keep in mind that at the end of your journey regarding fixing this bug you'd have to create a PR which will merge your fork with our original repository so don't make any unnecessary changes besides fixing the issue you're supposed to. 

For any other changes you create another issue and a different PR. 

For more information check out some YT tutorials on how to use GitHub.

Thanks, 
Alin!

**Comment by iamshrikantjha** [comment]
I want to make changes to the example branch of your github repo so kindly
add me to that.

That example branch which actually demonstrate the galio ui kit on expo.
I want to make changes to that only.

And correct me if I am wrong

Thanks

**Comment by shubhamkakkar** [comment]
Can someone elaborate this bug?

**Comment by palingheorghe** [comment]
@iamshrikantjha could you help us with more details regarding this bug?

**Comment by iamshrikantjha** [comment]
Actually what I am saying is that the drawer navigation items section is in
example branch of the project and I am unable to make changes to it because
I am not a part of it.
So kindly add me to that section of if I am wrong please let me know.

**Comment by palingheorghe** [comment]
Moved the galio-app to another repo called [galio-starter-kit](https://github.com/galio-org/galio-starter-kit). So all the issues regarding the app need to move there as well. Thank you! 🧜🏽‍♂️
