### ISSUE TITLE
add hitSlop to navbar left icon

### ISSUE THREAD

**Issue by zeritte** [galio-org/galio#91]
**The left navbar button is not user-friendly.**
Thank you for creating this awesome project. I want to add hitSlop to left navbar icon since without hitSlop it is really hard to use. I got too many feedbacks from test users about they are not able to click left button. I do not want to recreate a whole left component. 
the button I am talking about: (the one next to dashboard)
<img width="132" alt="Screen Shot 2019-06-09 at 12 05 44" src="https://user-images.githubusercontent.com/35241861/59157188-fe7c1c80-8aae-11e9-960e-baf5c9ac2d9e.png">

**Add leftHitSlop prop to Navbar.**
I want to control the touchable area. We can accomplish this by a slight difference; 
### current navbar component:

```
renderLeft = () => {
    const { back, left, leftStyle, leftIconColor, onLeftPress, theme, styles } = this.props;

    if (left) {
      return <View style={[styles.left, leftStyle]}>{left}</View>;
    }

    return (
      <View style={[styles.left, leftStyle]}>
        <TouchableOpacity onPress={() => onLeftPress && onLeftPress()}>
          <Icon
            family="Galio"
            color={leftIconColor || theme.COLORS.ICON}
            size={theme.SIZES.BASE * 1.0625}
            name={back ? 'minimal-left' : 'segmentation'}
          />
        </TouchableOpacity>
      </View>
    );
  };
```

### updated navbar component:

```
renderLeft = () => {
    const { back, left, leftStyle, leftIconColor, onLeftPress, theme, styles, leftHitSlop } = this.props;

    if (left) {
      return <View style={[styles.left, leftStyle]}>{left}</View>;
    }

    return (
      <View style={[styles.left, leftStyle]}>
        <TouchableOpacity
          onPress={() => onLeftPress && onLeftPress()}
          hitSlop={leftHitSlop}
        >
          <Icon
            family="Galio"
            color={leftIconColor || theme.COLORS.ICON}
            size={theme.SIZES.BASE * 1.0625}
            name={back ? "minimal-left" : "segmentation"}
          />
        </TouchableOpacity>
      </View>
    );
  };
```

please note the leftHitSlop prop.

### how to call this updated navbar component:
```
<NavBar
    style={styles.navbar}
    right={this.renderRight()}
    leftHitSlop={{ top: 30, bottom: 30, left: 30, right: 30 }}
    leftStyle={{ paddingVertical: -12, flex: 0.3 }}
    leftIconColor={theme.COLORS.WHITE}
    titleStyle={styles.title}
    onLeftPress={this.handleLeftPress}
/>
```

this is my first time opening an issue, please be merciful :)

**Comment by palingheorghe** [comment]
Hi @zeritte,

That's so cool, I'm glad you opened your first issue with Galio! Open up a PR regarding this issue and I'll sure accept it because this seems like a really good feature for our component! 

Thanks! ⭐️
