### ISSUE TITLE
The preview app doesn't run on new versions of expo client

### ISSUE THREAD

**Issue by gunn** [galio-org/galio#92]
The app at https://expo.io/@galio-framework/galio-native-kit uses expo SDK 29 which the latest clients don't support.
See https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c#dab0

![Screen Shot 2019-06-11 at 12 10 17 PM](https://user-images.githubusercontent.com/42500/59234830-92322200-8c42-11e9-9d7d-59bed05d1a10.png)

**Comment by palingheorghe** [comment]
Hi @gunn ! Thank you for opening up this issue! 
We'd have to update the app for our next version for sure! If anybody wants to try doing this in the meantime that'd be great! ❤️

Thanks,
Alin

**Comment by gunn** [comment]
Great. For someone who wanted to try, where is the source for the app?

**Comment by palingheorghe** [comment]
The `examples` branch contains the app. You could find more about our current set up on our [wiki](https://github.com/galio-org/galio/wiki) 🤙🏽.

**Comment by palingheorghe** [comment]
Hi @gunn ! I've updated the app from https://expo.io/@galio-framework/galio-native-kit ! I didn't update all the screens but some of them and the components screen are there for trying out! 


Thanks,
Alin

**Comment by Gease-RS** [comment]
I clone Repositorie https://github.com/galio-org/galio.git and got the following error:

`Your project is in SDK version >= 33.0.0, but the expo package version seems to be older.
Error: Can't find react-native in package.json dependencies
Cannot find module 'expo/tools/LogReporter'
Set EXPO_DEBUG=true in your env to view the stack trace.`

My packagen.json and node_module have react-native: 
`    "react": "16.8.3",
    "react-native": "^0.59",
    "react-native-vector-icons": "^6.5.0"
`

It looks like the SDK is not compatible with Expo, I tried to go back to the Expo version but couldn't.

Does anyone have any solutions? Thanks!

**Comment by palingheorghe** [comment]
Hi @Gease-RS ! Where did you clone the repo? The Galio `master` branch doesn't have an app so it can't work by itself. You need to install `galio` via `npm i galio-framework` inside one of your projects in order to use Galio as it should be used.

Thanks!

**Comment by Gease-RS** [comment]
@palingheorghe Ok! Thanks!

**Comment by toviszsolt** [comment]
![image](https://user-images.githubusercontent.com/18605518/103550587-6b34e400-4ea9-11eb-8d0d-9724f818f063.png)
