### ISSUE TITLE
Expo SDK 33.0.0 not working?

### ISSUE THREAD

**Issue by james-berry** [galio-org/galio#93]
Have just freshed installed Galio with `npm i --save galio-framework` on expo SDK 33. Am getting error:
`undefined is not an object (evaluating '_vectorIcons.default.Galio = (0, _vectorIcons.createIconSetFromIcoMoon)(_galio.default, 'Galio')')`

I commented out this line in galio-framework/src/Icon.js:
`// Icons.Galio = createIconSetFromIcoMoon(galioConfig, 'Galio');`

There is now no error, however no elements are rendering correctly as expected. E.g <Card /> from the docs.

Assume SDK 33 is just not supported yet?

**Comment by JOEAV** [comment]
same thing here. the author should upgrade expo dependencies

**Comment by palingheorghe** [comment]
Hi @james-berry @JOEAV ! Thanks for giving me a heads up! Yes, this needs to be fixed asap so people could use the framework. I'll update the dependencies. 

Thanks,
Alin

**Comment by JOEAV** [comment]
@palingheorghe  hey , can you give us an estimation when does the upgradge
should take place ? thanks in advanced

**Comment by palingheorghe** [comment]
Hi @JOEAV ! Yes, I'm going to push the changes today and remove Expo completely because it was only used for the Icon component. 

Alin

**Comment by james-berry** [comment]
@palingheorghe fantastic! many thanks in advance

**Comment by palingheorghe** [comment]
@JOEAV @james-berry You should now be able to install Galio v0.5.2 through npm/yarn. Please tell me if you encounter any more problems with it. I've written more about this patch update [here](https://github.com/galio-org/galio/releases/tag/v0.5.2). !

**Comment by aapav01** [comment]
```
> node_modules/galio-framework/src/Button.js 11:16
> Module parse failed: Unexpected token (11:16)
> You may need an appropriate loader to handle this file type.
> | 
> | class Button extends React.Component {
> >   renderContent = () => {
> |     const {
> |       loading,
```
I Getting this Error,
i have just setup an expo init <project> and yarn install galio-framework and imported it in my app

**Comment by pejoujarrar** [comment]
Hello, 

Please, any updates because I am encountering the same problem.
