### ISSUE TITLE
Error with new expo sdk 33.0.0 to open web app

### ISSUE THREAD

**Issue by SantiagoMolinaOrozco** [galio-org/galio#98]
**Describe the bug**
I get this error to open my project in the browser but not on android with new expo version

**To Reproduce**
1. Run  'expo start --web'
2. See error:

> node_modules/galio-framework/src/Button.js 11:16
> Module parse failed: Unexpected token (11:16)
> You may need an appropriate loader to handle this file type.
> | 
> | class Button extends React.Component {
> >   renderContent = () => {
> |     const {
> |       loading,

**Expected behavior**
Run project in the browser

**Smartphone (please complete the following information):**
 - Device: Linux deepin, Firefox
 - Type of device: Browser
 - React-Native version: [e.g. 0.58]
 - Expo version: [e.g. 33.0.0]

**Additional context**
I do not know what else may need, I hope to make myself understood

**Comment by palingheorghe** [comment]
Hi @SantiagoMolinaOrozco ! I haven't experimented with Expo web version yet so I'm not really sure what's the problem. We might have to try and update Galio but this doesn't have the biggest priority right now,.

**Comment by SantiagoMolinaOrozco** [comment]
@palingheorghe yeah, its a new feature from expo :see_no_evil: thanks for the fast answer.

**Comment by palingheorghe** [comment]
moved the conversation about Galio on web to #143 because this is version specific.
